題目：

array1 = np.array(range(30))



將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")
呈上題的 array，找出被 6 除餘 1 的數的索引

In [1]:
import numpy as np

In [2]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
array1.reshape(5,6,order="F")

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [10]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引
np.where(array1%6==1)

(array([ 1,  7, 13, 19, 25], dtype=int64),)